/*
 * Persona data: Joel Rasquinha (Strategic Partner Manager, Radix).
 * All companies, people and correspondence are fictional demo data.
 */
window.TITAN_PERSONAS = window.TITAN_PERSONAS || {};
window.TITAN_PERSONAS.joel = {
  id: 'joel',
  account: {
    name: 'Joel Rasquinha', email: 'joel.rasquinha@radix.website', brand: 'Radix',
    title: 'Strategic Partner Manager', website: 'radix.website', avatar: 'J',
    region: 'Global', currency: { code: 'USD', symbol: '$' },
  },
  pipelines: [{
    id: 'strategic-partnerships', name: 'Strategic Partnerships', entity: 'Opportunity',
    color: '#6b5aa8', defaultOwner: { name: 'Joel Rasquinha', email: 'joel.rasquinha@radix.website' },
    stages: ['Target account', 'Outreach', 'Discovery', 'Solution fit', 'Commercials', 'Contract review', 'Closed'],
    cards: [
      { id: 'joel-1', deal: 'GoDaddy registry partnership', company: 'GoDaddy', website: 'https://godaddy.com', contact: 'Maya Singh', value: 180000, stage: 'Target account', leadSource: 'Market research', lastActivity: '5d ago', activityType: 'Account researched', nextActivity: { type: 'task', label: 'Map decision makers', date: 'Aug 22' } },
      { id: 'joel-2', deal: 'Hostinger channel integration', company: 'Hostinger', website: 'https://hostinger.com', contact: 'Daniel Cho', value: 120000, stage: 'Outreach', leadSource: 'Conference', lastActivity: '1d ago', activityType: 'Email sent', threadRef: 'thread-orbithost' },
      { id: 'joel-3', deal: 'Wix domain portfolio partnership', company: 'Wix', website: 'https://wix.com', contact: 'Priya Nair', value: 240000, stage: 'Discovery', leadSource: 'Inbound', lastActivity: '3h ago', activityType: 'Meeting held', threadRef: 'thread-webnest' },
      { id: 'joel-4', deal: 'Squarespace marketplace integration', company: 'Squarespace', website: 'https://squarespace.com', contact: 'Avery Morgan', value: 165000, stage: 'Solution fit', leadSource: 'Partner referral', lastActivity: '2d ago', activityType: 'Technical review', nextActivity: { type: 'meeting', label: 'Integration design review', date: 'Aug 25, 3:00pm' } },
      { id: 'joel-5', deal: 'Shopify co-sell proposal', company: 'Shopify', website: 'https://shopify.com', contact: 'Sofia Alvarez', value: 320000, stage: 'Commercials', leadSource: 'Outbound', lastActivity: 'Today', activityType: 'Proposal sent', threadRef: 'thread-forgecart' },
      { id: 'joel-6', deal: 'Webflow reseller agreement', company: 'Webflow', website: 'https://webflow.com', contact: 'Theo Bennett', value: 275000, stage: 'Contract review', leadSource: 'Executive intro', lastActivity: '4d ago', activityType: 'Redlines received', threadRef: 'thread-studiostack' },
      { id: 'joel-7', deal: 'BigCommerce launch partnership', company: 'BigCommerce', website: 'https://bigcommerce.com', contact: 'Leila Haddad', value: 195000, stage: 'Closed', won: true, leadSource: 'Partner referral', lastActivity: '8d ago', activityType: 'Agreement signed', threadRef: 'thread-marketroot' },
      { id: 'joel-8', deal: 'SiteGround reseller opportunity', company: 'SiteGround', website: 'https://siteground.com', contact: 'Marcus Lee', value: 90000, stage: 'Closed', won: false, leadSource: 'Outbound', lastActivity: '18d ago', activityType: 'Opportunity closed lost', threadRef: 'thread-novapages' },
    ],
  }],
  mailbox: { threads: [
    { id: 'thread-orbithost', from: 'Daniel Cho', email: 'daniel.cho@hostinger.com', subject: 'Exploring a domain portfolio integration', date: 'Yesterday', unread: false, pipelineRef: { pipeline: 'strategic-partnerships', stage: 'Outreach', cardId: 'joel-2' }, messages: [{ dir: 'sent', when: 'Aug 18', body: ['Hi Daniel,', 'It was great meeting at the partner forum. I would like to compare Hostinger\'s customer journey with the registry and domain options Radix can support.', 'Best,\nJoel'] }, { dir: 'received', when: 'Yesterday', body: ['Hi Joel,', 'Happy to connect. Please send a few times next week and include our partnerships lead.', 'Daniel'] }] },
    { id: 'thread-webnest', from: 'Priya Nair', email: 'priya.nair@wix.com', subject: 'Discovery recap and next steps', date: 'Today', unread: true, pipelineRef: { pipeline: 'strategic-partnerships', stage: 'Discovery', cardId: 'joel-3' }, messages: [{ dir: 'received', when: '30 Jul', body: ['Hi Joel,', 'We are exploring a more focused domain portfolio for our creator audience. Could we learn how Radix approaches launch support and portfolio migration?', 'Priya'] }, { dir: 'sent', when: '5 Aug', body: ['Hi Priya,', 'Thank you for reaching out. I would be happy to compare the audience, timing and the domain options that could make sense for a phased launch.', 'Regards,\nJoel'] }, { dir: 'sent', when: '14 Aug', body: ['Hi Priya and Jon,', 'Attached is the proposed pilot scope. I have kept it focused on a limited domain set, a clear customer journey and agreed success measures before a broader rollout.', 'Best,\nJoel'] }, { dir: 'received', when: 'Today, 11:05am', body: ['Hi Joel,', 'The team liked the approach. A session with product and growth would help us validate the best launch path and what a first pilot would require.', 'Priya'] }, { dir: 'sent', when: 'Today, 1:40pm', body: ['Hi Priya,', 'Great. I have sent a hold for next Tuesday with our product team. I will share the domain shortlist and the open integration questions before then.', 'Thanks,\nJoel'] }] },
    { id: 'thread-forgecart', from: 'Sofia Alvarez', email: 'sofia.alvarez@shopify.com', subject: 'Re: Shopify co-sell proposal', date: 'Today', unread: false, pipelineRef: { pipeline: 'strategic-partnerships', stage: 'Commercials', cardId: 'joel-5' }, messages: [{ dir: 'sent', when: 'Today', body: ['Hi Sofia,', 'Attached is the commercial proposal with the phased launch plan and co-marketing contribution.', 'Best,\nJoel'] }, { dir: 'received', when: 'Today', body: ['Thanks Joel. We are reviewing the revenue model with finance and will return comments this week.', 'Sofia'] }] },
    { id: 'thread-studiostack', from: 'Theo Bennett', email: 'theo.bennett@webflow.com', subject: 'Re: Reseller agreement redlines', date: '4d ago', unread: true, pipelineRef: { pipeline: 'strategic-partnerships', stage: 'Contract review', cardId: 'joel-6' }, messages: [{ dir: 'received', when: '4d ago', body: ['Hi Joel,', 'Our legal team returned a limited set of redlines, mainly around support responsibilities and launch communications.', 'Theo'] }] },
    { id: 'thread-marketroot', from: 'Leila Haddad', email: 'leila.haddad@bigcommerce.com', subject: 'Signed: BigCommerce partnership agreement', date: '8d ago', unread: false, pipelineRef: { pipeline: 'strategic-partnerships', stage: 'Closed', cardId: 'joel-7' }, messages: [{ dir: 'received', when: '8d ago', body: ['Hi Joel,', 'The agreement is signed. Looking forward to planning the launch with your team.', 'Leila'] }] },
    { id: 'thread-novapages', from: 'Marcus Lee', email: 'marcus.lee@siteground.com', subject: 'Re: SiteGround partnership discussion', date: '18d ago', unread: false, pipelineRef: { pipeline: 'strategic-partnerships', stage: 'Closed', cardId: 'joel-8' }, messages: [{ dir: 'received', when: '18d ago', body: ['Hi Joel,', 'We have decided to pause new partnership work this quarter. Please keep in touch for a later review.', 'Marcus'] }] },
  ] },
  contacts: [
    { name: 'Maya Singh', email: 'maya.singh@godaddy.com', source: 'Market research' }, { name: 'Daniel Cho', email: 'daniel.cho@hostinger.com', source: 'Conference' }, { name: 'Priya Nair', email: 'priya.nair@wix.com', source: 'Inbound' }, { name: 'Avery Morgan', email: 'avery.morgan@squarespace.com', source: 'Partner referral' }, { name: 'Sofia Alvarez', email: 'sofia.alvarez@shopify.com', source: 'Outbound' }, { name: 'Theo Bennett', email: 'theo.bennett@webflow.com', source: 'Executive intro' }, { name: 'Leila Haddad', email: 'leila.haddad@bigcommerce.com', source: 'Partner referral' }, { name: 'Marcus Lee', email: 'marcus.lee@siteground.com', source: 'Outbound' },
  ],
};
